/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.32.0-60-g2bc3ec44b (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.32.0-60-g2bc3ec44b"
#endif
#define SDL_REVISION_NUMBER 0
